spring.application.name=avaliafit



#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:mysql://localhost:3306/avaliafit



#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=22021996



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

api.security.token.secret=2213
api.security.token.issuer=${spring.application.name}
